#pragma once

#include "inventory.h"

#define RECIPY_LAMP (u1[]){ITEM_TORCH,ITEM_TORCH,ITEM_TORCH,ITEM_TORCH,0}
#define RECIPY_BLOCKSTATION (u1[]){ITEM_STONEDUST,ITEM_STONEDUST,ITEM_STONEDUST,ITEM_STONEDUST,0}
#define RECIPY_CRAFTINGSTATION (u1[]){ITEM_STONEDUST,ITEM_STONEDUST,ITEM_STONEDUST,ITEM_STONEDUST,0}
#define RECIPY_STONEWALL (u1[]){ITEM_STONEDUST,ITEM_STONEDUST,ITEM_STONEDUST,ITEM_STONEDUST,0}
#define RECIPY_TORCH (u1[]){ITEM_TORCH,ITEM_TORCH,ITEM_TORCH,ITEM_TORCH,0}
#define RECIPY_CHEST (u1[]){ITEM_LOG,ITEM_LOG,ITEM_LOG,ITEM_LOG,0}

u1 craftButton(VEC2 pos,VEC2 button_pos,u1* item);
void craftItem(u4 item,VEC2 cursor);