#pragma once

#include "vec2.h"

#define TEXTURE16_SIZE 16
#define TEXTURE16_ROW_COUNT 4
#define TEXTURE16_ROW_SIZE (TEXTURE16_SIZE*TEXTURE16_ROW_COUNT)
#define TEXTURE16_RD_SIZE (1.0f/TEXTURE16_ROW_COUNT)
#define TEXTURE16_OFFSET(X) (X/TEXTURE16_ROW_COUNT*TEXTURE16_ROW_SIZE*TEXTURE16_SIZE+X%TEXTURE16_ROW_COUNT*TEXTURE16_SIZE)
#define TEXTURE16_RENDER(X) (VEC2){(f4)(X%TEXTURE16_ROW_COUNT)/TEXTURE16_ROW_COUNT,(f4)(X/TEXTURE16_ROW_COUNT)/TEXTURE16_ROW_COUNT}

void genTextures();
VEC2 texture16Render(u4 number);